TESTING = True
#Define some colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)

# Set the width and height of the screen [width, height]
WIDTH = 1000
HEIGHT = 750

# FPS is Frame Per Second
FPS = 40
CREATE_BIRD_DELAY = 40
CREATE_CLOUD_DELAY = 80
LAUNCH_FIREBALL_COOLDOWN = 20
CREATE_FLAP_DELAY = 10

#Directions
LEFT = 270
RIGHT = 90

DIRECTIONS = [LEFT, RIGHT]

#GAME MODES
GAME_LANDING_PAGE = 1
GAME_IN_SESSION = 2

PLAYER_SPAWN_X = WIDTH/2
PLAYER_SPAWN_Y = HEIGHT/2

LAUNCH_GIANT_FIREBALL_COOLDOWN = 80
